name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging, production]

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Step 4: Set Environment Variables
      - name: Set Environment Variables for ${{ matrix.environment }}
        run: echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: pytest tests/test_unit.py --junitxml=unit-test-results-${{ matrix.environment }}.xml --cov=.

      # Step 6: Run Integration Tests
      - name: Run Integration Tests
        run: pytest tests/test_integration.py --junitxml=integration-test-results-${{ matrix.environment }}.xml --cov=.

      # Step 7: Run E2E Tests
      - name: Run E2E Tests
        run: pytest tests/test_e2e.py --junitxml=e2e-test-results-${{ matrix.environment }}.xml --cov=.

      # Step 8: Upload Test Results
      - name: Upload Test Results for ${{ matrix.environment }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.environment }}
          path: |
            unit-test-results-${{ matrix.environment }}.xml
            integration-test-results-${{ matrix.environment }}.xml
            e2e-test-results-${{ matrix.environment }}.xml

      # Step 9: Upload Coverage to Codecov
      - name: Upload Coverage for ${{ matrix.environment }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: ${{ matrix.environment }}
          fail_ci_if_error: true
